language: swift

matrix:
  include:
    - os: linux
      dist: trusty
      language: generic
      sudo: required
    - os: osx
      osx_image: xcode10.1

env:
  - FIXTURE_PATH_SIMPLE=./Fixtures/simple/mock-config.yml

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source ./scripts/install_swift.sh; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then swiftlint; fi
  - swift build
  - swift test